[project]
name = "afrl"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "pandas>=2.3.0",
    "torch>=2.7.1",
    "torchvision>=0.22.1",
]
